### PR TITLE
fix(Dropdown): correct Dropdown types

### PR DESCRIPTION
**Pull request by FrogTheFrog**

### CODE REVIEW

**Comment by AAGaming00** [comment]
Is data displayed to the user? If so it should be ReactNode

**Comment by FrogTheFrog** [comment]
Nope, the only the label is displayed.

**Comment by AAGaming00** [comment]
> Nope, the only the label is displayed.

Do react nodes work as a label? If so that should be changed to ReactNode to allow for custom element labels.

**Comment by FrogTheFrog** [comment]
> > Nope, the only the label is displayed.
> 
> Do react nodes work as a label? If so that should be changed to ReactNode to allow for custom element labels.

You're correct, the do support nodes

**Review by AAGaming00 — APPROVED** [review]

**Pull request merged**
