### PR TITLE
feat(custom-components): add basic slider component

### PR DESCRIPTION
**Pull request by jessebofill**
This is a slider component without the added field stuff that comes with a SliderField, allowing it to work well inline with other components or other custom implementations.

### CODE REVIEW

**Review by AAGaming00 — CHANGES_REQUESTED** [review]
don't style the field, get the underlying component instead.

**Comment by jessebofill** [comment]
> don't style the field, get the underlying component instead.

There is no underlying component, it's just made up of divs.

**Comment by AAGaming00** [comment]
> > don't style the field, get the underlying component instead.
> 
> There is no underlying component, it's just made up of divs.

there is an underlying react component that each Field component wraps.

**Comment by jessebofill** [comment]
> > > don't style the field, get the underlying component instead.
> > 
> > 
> > There is no underlying component, it's just made up of divs.
> 
> there is an underlying react component that each Field component wraps.

ah i see it now, i was looking at the fallback component.

**Comment by jessebofill** [comment]
I'll go ahead and pr the unmodified slider component seperately, cus in my opinion this custom component still serves a purpose which is adds highlight on focus (the standalone slider doesn't) and in order to achieve the same effect using just the slider I would still need to style it in a similar manner. If you don't wanna accept this component then feel free to close this pr.

**Comment by AAGaming00** [comment]
The focus thing should easily be solved by wrapping it in a Field, as you can do for any other component.

**Pull request closed without merging**
