### PR TITLE
Extend CI for PRs

### PR DESCRIPTION
**Pull request by FrogTheFrog**

### CODE REVIEW

**Comment by FrogTheFrog** [comment]
I should just go to sleep LOL

**Comment by FrogTheFrog** [comment]
I think this is ready @AAGaming00, unless you want a little bit more complicated chain. I have tested this on my main branch and the release step is indeed executed as expected on push, but not on PR.

Also, now that we do the Build step on both PR and push, the `semantic-release-bot` will no longer increment the version when it tries to build it itself and fails

**Comment by AAGaming00** [comment]
Wouldn't this build twice because of `prepack` in package.json?

**Comment by FrogTheFrog** [comment]
> Wouldn't this build twice because of `prepack` in package.json?

Not anymore

**Review by AAGaming00 — APPROVED** [review]
LGTM

**Pull request merged**
