### PR TITLE
feat(deck-components): add standalone slider component

### PR DESCRIPTION
**Pull request by jessebofill**
This is just the built in slider component. Note that this component does not give any indication of when it's focused, as that's normally indicated by the field.

### CODE REVIEW

**Comment by beebls** [comment]
Code all looks good, do you have a plugin that uses this so we can test?

**Comment by AAGaming00** [comment]
are you sure this isn't just a property of CommonUI?

**Comment by jessebofill** [comment]
> Code all looks good, do you have a plugin that uses this so we can test?

No, I don't. I just found it yesterday per AA's request.



> are you sure this isn't just a property of CommonUIModule?

Ah indeed you are correct. I'll change that. Is there a reason why the other components are still found by toString'ing  as opposed to just using the property name?

**Comment by AAGaming00** [comment]
> Ah indeed you are correct. I'll change that. Is there a reason why the other components are still found by toString'ing  as opposed to just using the property name?

iirc that's only the ones that are outside commonui

also commonui didn't have names at all until like June, so some of the old code works that way, we should probably refactor that soon

**Pull request closed without merging**
