### PR TITLE
feat(static-classes): added VirtualKeyboardContainerClasses

### PR DESCRIPTION
**Pull request by CarJem**

### CODE REVIEW

**Review by AAGaming00 — CHANGES_REQUESTED** [review]
Please properly format your commit messages and run Prettier.

**Comment by CarJem** [comment]
You can review the changes now if you want

**Review by AAGaming00 — APPROVED** [review]
code lgtm, will test soon

**Comment by beebls** [comment]
image
A console log of the specified module shows one additional property that isn't listed there, please add `ModalVirtualKeyboardContainer` to the Record.

**Review by beebls — CHANGES_REQUESTED** [review]
image
A console log of the specified module shows one additional property that isn't listed there, please add `ModalVirtualKeyboardContainer` to the Record.

**Comment by TrainDoctor** [comment]
Author has requested PR be closed.

**Pull request closed without merging**
